module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- 
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "plane.png",
                spriteColorRect = { x = 0, y = 0, width = 127, height = 98 },
                textureRect = { x = 0, y = 0, width = 127, height = 98 },
                spriteSourceSize = { width = 127, height = 98 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "rocket.png",
                spriteColorRect = { x = 0, y = 0, width = 13, height = 35 },
                textureRect = { x = 0, y = 98, width = 13, height = 35 },
                spriteSourceSize = { width = 13, height = 35 },
                spriteTrimmed = false,
                textureRotated = false
            },
        }
    }
    return sheet
end

