-- Generated by Level Director v2.7.0 on 19.04.2014 16:49:18 --
module(..., package.seeall)

require("lib.LD_HelperG2")

-----------------------------------
function loadAssets()
-----------------------------------
	local assets = {}
	assets.spriteSheetData = {}
	

	assets['beam_png']={
		file = 'beam.png',
		name = 'beam_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 295,
		height = 158,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['bush_png']={
		file = 'bush.png',
		name = 'bush_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 249,
		height = 207,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['callboard_png']={
		file = 'callboard.png',
		name = 'callboard_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 275,
		height = 254,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['fence_png']={
		file = 'fence.png',
		name = 'fence_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 375,
		height = 181,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['grass1_png']={
		file = 'grass1.png',
		name = 'grass1_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 306,
		height = 204,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['grave_png']={
		file = 'grave.png',
		name = 'grave_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 230,
		height = 265,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['plant_png']={
		file = 'plant.png',
		name = 'plant_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 253,
		height = 239,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['stone1_png']={
		file = 'stone1.png',
		name = 'stone1_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 170,
		height = 96,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['stone2_png']={
		file = 'stone2.png',
		name = 'stone2_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 223,
		height = 138,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['stump_png']={
		file = 'stump.png',
		name = 'stump_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 214,
		height = 189,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['tree1_png']={
		file = 'tree1.png',
		name = 'tree1_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 222,
		height = 468,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['tree2_png']={
		file = 'tree2.png',
		name = 'tree2_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 247,
		height = 412,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['tree3_png']={
		file = 'tree3.png',
		name = 'tree3_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 250,
		height = 505,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['trod_png']={
		file = 'trod.png',
		name = 'trod_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 282,
		height = 318,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	assets['wc_png']={
		file = 'wc.png',
		name = 'wc_png',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 197,
		height = 221,
		frame = 0,
		spriteSheetName = '',
		frameCount = 0,
		sequenceData = {},
		sequenceInfo = {default = '', play= false },

		physics	= 	{	isEnabled = false, source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}
	
	return assets
end -- loadAssets


-------------------------------
function createLevel()
-------------------------------
	local objProps = {}
	local level = {}
    local obj = nil
	
	if (application.LevelDirectorSettings.viewGroup == nil) then
		level.view = display.newGroup() 
	else
		level.view = application.LevelDirectorSettings.viewGroup
	end
	
	level.view.anchorChildren =false 
	
	display.setDefault( 'background',  105 / 255, 105 / 255, 105 / 255, 255 / 255)
	display.setDefault( "anchorX", 0.5 )
	display.setDefault( "anchorY", 0.5 )	
	display.setDrawMode("wireframe",false)
	
	level.name = 'New Level' 
	
	-- Load Assets
	level.assets = loadAssets()

	-- Physics properties
	physics.setGravity(0,9.80000019073486) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	
	level.parallaxEnabled = false
	
	-- Layers
	level.layers = {} 
	---- New Layer ----
	level.layers['New Layer'] = {} 
	level.layers['New Layer'].view = display.newGroup() 
	level.layers['New Layer'].name = 'New Layer' 
	
	if (level.parallaxEnabled) then
		level.layers['New Layer'].speed = {x = 0, y = 0}
		level.layers['New Layer'].repeated = false
	end
	
	level.layers['New Layer'].objects = {} 

	objProps = 
	{
		name 	= 'img_1', 
		objType = 'LDObjectImage',
		class = '',
		width	= 197,
		height	= 221,
		x		= 194,
		y		= 118,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0.5,
		anchorY = 0.5,
		alpha = 1,
		isVisible = true,
		assetName	= 'wc_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['New Layer'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_3', 
		objType = 'LDObjectImage',
		class = '',
		width	= 170,
		height	= 96,
		x		= 93,
		y		= 262,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0.5,
		anchorY = 0.5,
		alpha = 1,
		isVisible = true,
		assetName	= 'stone1_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['New Layer'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_6', 
		objType = 'LDObjectImage',
		class = '',
		width	= 282,
		height	= 318,
		x		= 211,
		y		= 447,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0.5,
		anchorY = 0.5,
		alpha = 1,
		isVisible = true,
		assetName	= 'trod_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['New Layer'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_8', 
		objType = 'LDObjectImage',
		class = '',
		width	= 282,
		height	= 318,
		x		= 359,
		y		= 697,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0.5,
		anchorY = 0.5,
		alpha = 1,
		isVisible = true,
		assetName	= 'trod_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['New Layer'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_10', 
		objType = 'LDObjectImage',
		class = '',
		width	= 282,
		height	= 318,
		x		= 303,
		y		= 991,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0.5,
		anchorY = 0.5,
		alpha = 1,
		isVisible = true,
		assetName	= 'trod_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['New Layer'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_14', 
		objType = 'LDObjectImage',
		class = '',
		width	= 214,
		height	= 189,
		x		= 173,
		y		= 750,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0.5,
		anchorY = 0.5,
		alpha = 1,
		isVisible = true,
		assetName	= 'stump_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['New Layer'],objProps, level.assets) 
	
	objProps = 
	{
		name 	= 'img_16', 
		objType = 'LDObjectImage',
		class = '',
		width	= 222,
		height	= 468,
		x		= 535,
		y		= 232,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0.5,
		anchorY = 0.5,
		alpha = 1,
		isVisible = true,
		assetName	= 'tree1_png',
		physics	= 	{	isEnabled = false, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = true,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
						}
					}
						
		}
	obj = LD_Helper:instance():createObject(level.layers['New Layer'],objProps, level.assets) 
	
	LD_Helper:instance():insertLayer(level,level.layers['New Layer'])
	
	--level.ldVersion = 2.7.0	-- Level Director Version
	
	-- Parallax (after layers)
	level.canvasWidth = 640
	level.canvasHeight = 1136
	
	if level.parallaxEnabled then
		level.parallaxInfinite = false
		level.parallaxDamping = 1
		LD_Helper:instance():createParallax(level)
	end

	
	
	return level
end -- createLevel

