module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- 
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "back1.png",
                spriteColorRect = { x = 0, y = 0, width = 320, height = 568 },
                textureRect = { x = 0, y = 0, width = 320, height = 568 },
                spriteSourceSize = { width = 320, height = 568 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "beam.png",
                spriteColorRect = { x = 0, y = 0, width = 295, height = 158 },
                textureRect = { x = 320, y = 0, width = 295, height = 158 },
                spriteSourceSize = { width = 295, height = 158 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "bush.png",
                spriteColorRect = { x = 0, y = 0, width = 249, height = 207 },
                textureRect = { x = 615, y = 0, width = 249, height = 207 },
                spriteSourceSize = { width = 249, height = 207 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "callboard.png",
                spriteColorRect = { x = 0, y = 0, width = 275, height = 254 },
                textureRect = { x = 0, y = 568, width = 275, height = 254 },
                spriteSourceSize = { width = 275, height = 254 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "fence.png",
                spriteColorRect = { x = 0, y = 0, width = 375, height = 181 },
                textureRect = { x = 275, y = 568, width = 375, height = 181 },
                spriteSourceSize = { width = 375, height = 181 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "grass1.png",
                spriteColorRect = { x = 0, y = 0, width = 306, height = 204 },
                textureRect = { x = 650, y = 568, width = 306, height = 204 },
                spriteSourceSize = { width = 306, height = 204 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "grave.png",
                spriteColorRect = { x = 0, y = 0, width = 230, height = 265 },
                textureRect = { x = 0, y = 822, width = 230, height = 265 },
                spriteSourceSize = { width = 230, height = 265 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "plant.png",
                spriteColorRect = { x = 0, y = 0, width = 253, height = 239 },
                textureRect = { x = 230, y = 822, width = 253, height = 239 },
                spriteSourceSize = { width = 253, height = 239 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "stone1.png",
                spriteColorRect = { x = 0, y = 0, width = 170, height = 96 },
                textureRect = { x = 483, y = 822, width = 170, height = 96 },
                spriteSourceSize = { width = 170, height = 96 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "stone2.png",
                spriteColorRect = { x = 0, y = 0, width = 223, height = 138 },
                textureRect = { x = 653, y = 822, width = 223, height = 138 },
                spriteSourceSize = { width = 223, height = 138 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "stump.png",
                spriteColorRect = { x = 0, y = 0, width = 214, height = 189 },
                textureRect = { x = 0, y = 1087, width = 214, height = 189 },
                spriteSourceSize = { width = 214, height = 189 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "tree1.png",
                spriteColorRect = { x = 0, y = 0, width = 222, height = 468 },
                textureRect = { x = 214, y = 1087, width = 222, height = 468 },
                spriteSourceSize = { width = 222, height = 468 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "tree2.png",
                spriteColorRect = { x = 0, y = 0, width = 247, height = 412 },
                textureRect = { x = 436, y = 1087, width = 247, height = 412 },
                spriteSourceSize = { width = 247, height = 412 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "tree3.png",
                spriteColorRect = { x = 0, y = 0, width = 250, height = 505 },
                textureRect = { x = 683, y = 1087, width = 250, height = 505 },
                spriteSourceSize = { width = 250, height = 505 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "trod.png",
                spriteColorRect = { x = 0, y = 0, width = 282, height = 318 },
                textureRect = { x = 0, y = 1592, width = 282, height = 318 },
                spriteSourceSize = { width = 282, height = 318 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "wc.png",
                spriteColorRect = { x = 0, y = 0, width = 197, height = 221 },
                textureRect = { x = 282, y = 1592, width = 197, height = 221 },
                spriteSourceSize = { width = 197, height = 221 },
                spriteTrimmed = false,
                textureRotated = false
            },
        }
    }
    return sheet
end

