module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- 
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "Chicken0001.png",
                spriteColorRect = { x = 19, y = 0, width = 166, height = 141 },
                textureRect = { x = 0, y = 0, width = 166, height = 141 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0002.png",
                spriteColorRect = { x = 15, y = 0, width = 172, height = 139 },
                textureRect = { x = 166, y = 0, width = 172, height = 139 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0003.png",
                spriteColorRect = { x = 14, y = 2, width = 176, height = 135 },
                textureRect = { x = 338, y = 0, width = 176, height = 135 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0004.png",
                spriteColorRect = { x = 10, y = 2, width = 184, height = 133 },
                textureRect = { x = 514, y = 0, width = 184, height = 133 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0005.png",
                spriteColorRect = { x = 8, y = 3, width = 188, height = 131 },
                textureRect = { x = 698, y = 0, width = 188, height = 131 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0006.png",
                spriteColorRect = { x = 6, y = 6, width = 190, height = 127 },
                textureRect = { x = 0, y = 141, width = 190, height = 127 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0007.png",
                spriteColorRect = { x = 6, y = 6, width = 188, height = 127 },
                textureRect = { x = 190, y = 141, width = 188, height = 127 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0008.png",
                spriteColorRect = { x = 7, y = 5, width = 186, height = 127 },
                textureRect = { x = 378, y = 141, width = 186, height = 127 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0009.png",
                spriteColorRect = { x = 6, y = 4, width = 188, height = 129 },
                textureRect = { x = 564, y = 141, width = 188, height = 129 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0010.png",
                spriteColorRect = { x = 6, y = 4, width = 190, height = 129 },
                textureRect = { x = 752, y = 141, width = 190, height = 129 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0011.png",
                spriteColorRect = { x = 8, y = 3, width = 188, height = 131 },
                textureRect = { x = 0, y = 270, width = 188, height = 131 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0012.png",
                spriteColorRect = { x = 10, y = 2, width = 184, height = 133 },
                textureRect = { x = 188, y = 270, width = 184, height = 133 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0013.png",
                spriteColorRect = { x = 14, y = 1, width = 176, height = 135 },
                textureRect = { x = 372, y = 270, width = 176, height = 135 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0014.png",
                spriteColorRect = { x = 15, y = 0, width = 172, height = 139 },
                textureRect = { x = 548, y = 270, width = 172, height = 139 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Chicken0015.png",
                spriteColorRect = { x = 19, y = 0, width = 166, height = 141 },
                textureRect = { x = 720, y = 270, width = 166, height = 141 },
                spriteSourceSize = { width = 202, height = 151 },
                spriteTrimmed = true,
                textureRotated = false
            },
        }
    }
    return sheet
end

