module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- 
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "Egg0001.png",
                spriteColorRect = { x = 6, y = 17, width = 114, height = 139 },
                textureRect = { x = 466, y = 403, width = 114, height = 139 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0002.png",
                spriteColorRect = { x = 6, y = 17, width = 114, height = 139 },
                textureRect = { x = 0, y = 0, width = 114, height = 139 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0003.png",
                spriteColorRect = { x = 4, y = 19, width = 116, height = 137 },
                textureRect = { x = 114, y = 0, width = 116, height = 137 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0004.png",
                spriteColorRect = { x = 4, y = 21, width = 116, height = 135 },
                textureRect = { x = 230, y = 0, width = 116, height = 135 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0005.png",
                spriteColorRect = { x = 3, y = 21, width = 118, height = 135 },
                textureRect = { x = 346, y = 0, width = 118, height = 135 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0006.png",
                spriteColorRect = { x = 3, y = 23, width = 118, height = 133 },
                textureRect = { x = 464, y = 0, width = 118, height = 133 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0007.png",
                spriteColorRect = { x = 3, y = 23, width = 118, height = 133 },
                textureRect = { x = 582, y = 0, width = 118, height = 133 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0008.png",
                spriteColorRect = { x = 2, y = 25, width = 120, height = 131 },
                textureRect = { x = 700, y = 0, width = 120, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0009.png",
                spriteColorRect = { x = 2, y = 26, width = 120, height = 131 },
                textureRect = { x = 820, y = 0, width = 120, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0010.png",
                spriteColorRect = { x = 1, y = 27, width = 122, height = 131 },
                textureRect = { x = 0, y = 139, width = 122, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0011.png",
                spriteColorRect = { x = 1, y = 28, width = 122, height = 131 },
                textureRect = { x = 122, y = 139, width = 122, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0012.png",
                spriteColorRect = { x = 1, y = 30, width = 122, height = 131 },
                textureRect = { x = 244, y = 139, width = 122, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0013.png",
                spriteColorRect = { x = 0, y = 31, width = 124, height = 131 },
                textureRect = { x = 366, y = 139, width = 124, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0014.png",
                spriteColorRect = { x = 0, y = 32, width = 124, height = 131 },
                textureRect = { x = 490, y = 139, width = 124, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0015.png",
                spriteColorRect = { x = 0, y = 33, width = 124, height = 131 },
                textureRect = { x = 614, y = 139, width = 124, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0016.png",
                spriteColorRect = { x = 0, y = 32, width = 124, height = 131 },
                textureRect = { x = 738, y = 139, width = 124, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0017.png",
                spriteColorRect = { x = 0, y = 31, width = 124, height = 131 },
                textureRect = { x = 862, y = 139, width = 124, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0018.png",
                spriteColorRect = { x = 1, y = 30, width = 122, height = 131 },
                textureRect = { x = 0, y = 270, width = 122, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0019.png",
                spriteColorRect = { x = 1, y = 29, width = 122, height = 131 },
                textureRect = { x = 122, y = 270, width = 122, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0020.png",
                spriteColorRect = { x = 1, y = 28, width = 122, height = 131 },
                textureRect = { x = 244, y = 270, width = 122, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0021.png",
                spriteColorRect = { x = 2, y = 26, width = 120, height = 131 },
                textureRect = { x = 366, y = 270, width = 120, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0022.png",
                spriteColorRect = { x = 2, y = 26, width = 120, height = 131 },
                textureRect = { x = 486, y = 270, width = 120, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0023.png",
                spriteColorRect = { x = 2, y = 25, width = 120, height = 131 },
                textureRect = { x = 606, y = 270, width = 120, height = 131 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0024.png",
                spriteColorRect = { x = 3, y = 23, width = 118, height = 133 },
                textureRect = { x = 726, y = 270, width = 118, height = 133 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0025.png",
                spriteColorRect = { x = 3, y = 23, width = 118, height = 133 },
                textureRect = { x = 844, y = 270, width = 118, height = 133 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0026.png",
                spriteColorRect = { x = 3, y = 21, width = 118, height = 135 },
                textureRect = { x = 0, y = 403, width = 118, height = 135 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0027.png",
                spriteColorRect = { x = 4, y = 21, width = 116, height = 135 },
                textureRect = { x = 118, y = 403, width = 116, height = 135 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0028.png",
                spriteColorRect = { x = 4, y = 19, width = 116, height = 137 },
                textureRect = { x = 234, y = 403, width = 116, height = 137 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0029.png",
                spriteColorRect = { x = 4, y = 17, width = 116, height = 139 },
                textureRect = { x = 350, y = 403, width = 116, height = 139 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0030.png",
                spriteColorRect = { x = 6, y = 17, width = 114, height = 139 },
                textureRect = { x = 466, y = 403, width = 114, height = 139 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0031.png",
                spriteColorRect = { x = 0, y = 28, width = 124, height = 129 },
                textureRect = { x = 580, y = 403, width = 124, height = 129 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0032.png",
                spriteColorRect = { x = 3, y = 20, width = 118, height = 139 },
                textureRect = { x = 704, y = 403, width = 118, height = 139 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0033.png",
                spriteColorRect = { x = 7, y = 9, width = 110, height = 157 },
                textureRect = { x = 822, y = 403, width = 110, height = 157 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Egg0034.png",
                spriteColorRect = { x = 12, y = 0, width = 102, height = 173 },
                textureRect = { x = 0, y = 560, width = 102, height = 173 },
                spriteSourceSize = { width = 124, height = 173 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "weapon.png",
                spriteColorRect = { x = 0, y = 0, width = 69, height = 72 },
                textureRect = { x = 102, y = 560, width = 69, height = 72 },
                spriteSourceSize = { width = 69, height = 72 },
                spriteTrimmed = false,
                textureRotated = false
            },
        }
    }
    return sheet
end

