module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- 
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "Pig0001.png",
                spriteColorRect = { x = 29, y = 7, width = 202, height = 238 },
                textureRect = { x = 816, y = 466, width = 202, height = 238 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0002.png",
                spriteColorRect = { x = 29, y = 6, width = 202, height = 238 },
                textureRect = { x = 0, y = 0, width = 202, height = 238 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0003.png",
                spriteColorRect = { x = 28, y = 7, width = 204, height = 236 },
                textureRect = { x = 202, y = 0, width = 204, height = 236 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0004.png",
                spriteColorRect = { x = 28, y = 9, width = 204, height = 232 },
                textureRect = { x = 406, y = 0, width = 204, height = 232 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0005.png",
                spriteColorRect = { x = 27, y = 10, width = 206, height = 230 },
                textureRect = { x = 610, y = 0, width = 206, height = 230 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0006.png",
                spriteColorRect = { x = 27, y = 10, width = 206, height = 228 },
                textureRect = { x = 816, y = 0, width = 206, height = 228 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0007.png",
                spriteColorRect = { x = 26, y = 11, width = 208, height = 226 },
                textureRect = { x = 0, y = 238, width = 208, height = 226 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0008.png",
                spriteColorRect = { x = 26, y = 12, width = 208, height = 224 },
                textureRect = { x = 208, y = 238, width = 208, height = 224 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0009.png",
                spriteColorRect = { x = 26, y = 11, width = 208, height = 226 },
                textureRect = { x = 416, y = 238, width = 208, height = 226 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0010.png",
                spriteColorRect = { x = 27, y = 10, width = 206, height = 228 },
                textureRect = { x = 624, y = 238, width = 206, height = 228 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0011.png",
                spriteColorRect = { x = 27, y = 10, width = 206, height = 230 },
                textureRect = { x = 0, y = 466, width = 206, height = 230 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0012.png",
                spriteColorRect = { x = 28, y = 9, width = 204, height = 232 },
                textureRect = { x = 206, y = 466, width = 204, height = 232 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0013.png",
                spriteColorRect = { x = 28, y = 7, width = 204, height = 236 },
                textureRect = { x = 410, y = 466, width = 204, height = 236 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0014.png",
                spriteColorRect = { x = 29, y = 6, width = 202, height = 238 },
                textureRect = { x = 614, y = 466, width = 202, height = 238 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0015.png",
                spriteColorRect = { x = 29, y = 7, width = 202, height = 238 },
                textureRect = { x = 816, y = 466, width = 202, height = 238 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0016.png",
                spriteColorRect = { x = 29, y = 7, width = 202, height = 238 },
                textureRect = { x = 816, y = 466, width = 202, height = 238 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0017.png",
                spriteColorRect = { x = 29, y = 6, width = 202, height = 240 },
                textureRect = { x = 0, y = 704, width = 202, height = 240 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0018.png",
                spriteColorRect = { x = 29, y = 6, width = 204, height = 240 },
                textureRect = { x = 202, y = 704, width = 204, height = 240 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0019.png",
                spriteColorRect = { x = 28, y = 4, width = 210, height = 242 },
                textureRect = { x = 406, y = 704, width = 210, height = 242 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0020.png",
                spriteColorRect = { x = 28, y = 4, width = 214, height = 242 },
                textureRect = { x = 616, y = 704, width = 214, height = 242 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0021.png",
                spriteColorRect = { x = 29, y = 7, width = 202, height = 238 },
                textureRect = { x = 816, y = 466, width = 202, height = 238 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0022.png",
                spriteColorRect = { x = 29, y = 6, width = 202, height = 240 },
                textureRect = { x = 0, y = 946, width = 202, height = 240 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0023.png",
                spriteColorRect = { x = 29, y = 6, width = 202, height = 242 },
                textureRect = { x = 202, y = 946, width = 202, height = 242 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0024.png",
                spriteColorRect = { x = 29, y = 7, width = 202, height = 242 },
                textureRect = { x = 404, y = 946, width = 202, height = 242 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0025.png",
                spriteColorRect = { x = 26, y = 7, width = 206, height = 244 },
                textureRect = { x = 606, y = 946, width = 206, height = 244 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0026.png",
                spriteColorRect = { x = 29, y = 7, width = 202, height = 238 },
                textureRect = { x = 816, y = 466, width = 202, height = 238 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0027.png",
                spriteColorRect = { x = 26, y = 14, width = 210, height = 226 },
                textureRect = { x = 812, y = 946, width = 210, height = 226 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0028.png",
                spriteColorRect = { x = 13, y = 17, width = 238, height = 218 },
                textureRect = { x = 0, y = 1190, width = 238, height = 218 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "Pig0029.png",
                spriteColorRect = { x = 29, y = 7, width = 202, height = 238 },
                textureRect = { x = 816, y = 466, width = 202, height = 238 },
                spriteSourceSize = { width = 264, height = 256 },
                spriteTrimmed = true,
                textureRotated = false
            },
        }
    }
    return sheet
end

