module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- 
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "Exp_type_A_01.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_02.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_03.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_04.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_05.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_06.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_07.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_08.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_09.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_10.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_11.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_12.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_13.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_14.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_15.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_16.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_17.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_18.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_19.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_20.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_21.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_22.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_23.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_24.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_25.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_26.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_27.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_28.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_29.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_30.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_31.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_32.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_33.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_34.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_35.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_36.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_37.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_38.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_39.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "Exp_type_A_40.png",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
        }
    }
    return sheet
end

